name: >-
  Create a marketplace update pull request from head branch to base branch

on:
  # Run whenever new commits are pushed to the target branches defined as gibelow.
  push:
    branches:
      - 'marketplace_updates' # only track the marketplace_updates branch
  # Run by manual trigger
  workflow_dispatch:
    inputs:
      base-branch:
        description: >-
          The base branch that a versioning branch will be based.
        required: true
        default: main
jobs:
  main_job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - name: create pr
        id: create-pr
        uses: fortinet/github-action-version-pr@1.0.3
        with:
          base-branch: marketplace_updates
          head-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-create-draft: false
          pr-fail-if-exist: false
          pr-template-uri: .github/workflows/templates/marketplace-updates-pr.yml
